/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.springframework.boot:spring-boot-starter-web:2.2.6.RELEASE")
    api("org.slf4j:slf4j-api:2.0.0-alpha0")
    api("org.springframework.integration:spring-integration-stream:5.2.5.RELEASE")
    api("org.springframework.integration:spring-integration-mqtt:5.2.5.RELEASE")
    api("org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5")
}

group = "org.example"
version = "0.0.1-SNAPSHOT"
description = "mqtt_spring"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
