mqtt:
  url : ${url}
  port: 1883
  qos: 0
  topic: ${topic}
  username : ${username}
  password : ${password}
spring:
    main:
      web-application-type: none

es:
  url: localhost
  port: 9200

#https://github.com/sematext/logagent-js/blob/master/config/examples/elasticsearch-http-input_mqtt-output.yml