mqtt:
  url : ${url}
  port: 1883
  qos: 0
  topic: ${topic}
  username : ${username}
  password : ${password}
spring:
    main:
      web-application-type: none

elasticsearch:
  host: localhost
  port: 9200

logging:
  level:
    org.springframework: INFO

#https://velog.io/@leejw951208/Spring-Data-Elasticsearch-%EC%97%B0%EB%8F%99